//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnEnglish
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnglishEntities : DbContext
    {
        public EnglishEntities()
            : base("name=EnglishEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Story> Stories { get; set; }
        public virtual DbSet<Story_Word> Story_Word { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<Word> Words { get; set; }
    }
}
