//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnEnglish
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story_Word
    {
        public long ID { get; set; }
        public long IDWord { get; set; }
        public long IDStory { get; set; }
    
        public virtual Story Story { get; set; }
        public virtual Word Word { get; set; }
    }
}
